name: ci
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  wither:
    runs-on: ubuntu-latest
    container: rust:1.44-slim-buster
    strategy:
      matrix:
        mongo_version: ["mongo:4.2", "mongo:4.0", "mongo:3.6"]
        features: ["--features=tokio-runtime", "--no-default-features --features=async-std-runtime"]
    services:
      mongo:
        image: ${{ matrix.mongo_version }}
    env:
      HOST: mongo
      PORT: 27017
    steps:
    - uses: actions/checkout@v2
    - name: install clippy
      run: rustup component add clippy
    - name: build
      run: cargo build
    - name: clippy
      run: cargo clippy
    - name: test wither
      run: cd wither; cargo test ${{ matrix.features }} --tests --lib -- --test-threads=1; cd -
    - name: test wither derive
      run: cd wither_derive; cargo test --tests --lib; cd -

  wither-derive:
    runs-on: ubuntu-latest
    container: rust:1.44-slim-buster
    steps:
    - uses: actions/checkout@v2
    - name: test wither_derive
      run: cd wither_derive; cargo test --tests --lib; cd -

  doc:
    runs-on: ubuntu-latest
    container: rust:1.44-slim-buster
    steps:
    - uses: actions/checkout@v2
    - name: install nightly
      run: rustup install nightly-2020-05-25
    - name: test wither docs
      run: cd wither && cargo +nightly-2020-05-25 test --features docinclude --doc; cd -
    - name: test wither docs
      run: cd wither_derive && cargo +nightly-2020-05-25 test --doc; cd -
