name: ci
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p wither -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  wither:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongo_version: ["mongo:4.2", "mongo:4.0", "mongo:3.6"]
        features: ["--features=tokio-runtime", "--no-default-features --features=async-std-runtime"]
    services:
      mongo:
        image: ${{ matrix.mongo_version }}
        ports:
          - 27017:27017
    env:
      HOST: localhost
      PORT: 27017
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.features }} --tests --lib --manifest-path wither/Cargo.toml -- --test-threads=1

  wither_derive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p wither_derive -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p wither_derive --tests --lib

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-05-25
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features docinclude --doc --manifest-path wither/Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --manifest-path wither_derive/Cargo.toml
